blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('tag/<str:slug>', views.tag_page),
    path('category/<str:slug>', views.category_page),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('blog_list/', views.PostList.as_view(), name='blog_list'),
]

django_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('blog/', include('blog.urls')),
    path("admin/", admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('single_pages.urls')),
    path('users/', include('users.urls')),
    path('notice/', include('notice.urls')),
    path('free/', include('free.urls')),
    path('anonymous/', include('anonymous.urls')),
    path('calender/', include('calender.urls')),
    path('about/', include('about.urls')),
    path('board/', include('board.urls')),



]




if settings.DEBUG:

    urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

free/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib import messages
from django.shortcuts import redirect


app_name = 'free'

def protected_file(request, path, document_root=None):
    messages.error(request, "접근 불가")
    return redirect('/')

urlpatterns = [
    path('all_list', views.AllListView.as_view(), name='all_list'),
    path('free/', views.FreeListView.as_view(), name='free_list'),
    path('question/', views.QuestionListView.as_view(), name='question_list'),
    path('information/', views.InformationListView.as_view(), name='information_list'),

    path('write/', views.free_write_view, name='free_write'),
    path('<int:pk>/', views.free_detail_view, name='free_detail'),
    path('<int:pk>/edit/', views.free_edit_view, name='free_edit'),
    path('<int:pk>/delete/', views.free_delete_view, name='free_delete'),
    path('download/<int:pk>', views.free_download_view, name="free_download"),

    path('<int:pk>/comment/write/', views.comment_write_view, name='comment_write'),
    path('<int:pk>/comment/delete/', views.comment_delete_view, name='comment_delete'),
]

urlpatterns += static(settings.MEDIA_URL, protected_file, document_root=settings.MEDIA_ROOT)

free/models.py
import os
from uuid import uuid4

from django.conf import settings
from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta
from django.contrib.auth.models import User
from django.apps import apps

def get_file_path(instance, filename):
    ymd_path = datetime.now().strftime('%Y/%m/%d')
    uuid_name = uuid4().hex
    return '/'.join(['upload_file/', ymd_path, uuid_name])


CATEGORY_CHOICES = (
    ("자유", "자유"),
    ("질문", "질문"),
    ("정보", "정보"),
)

class Free(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='작성자')
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=18, verbose_name='분류', default='자유')
    title = models.CharField(max_length=128, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    hits = models.PositiveIntegerField(verbose_name='조회수', default=0)
    comments = models.PositiveIntegerField(verbose_name='댓글수', null=True)
    files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='이미지파일')  # summernote MultiValueDict : files
    upload_files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='파일')
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')
    filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')

    def __str__(self):
        return self.title


    def delete(self, *args, **kargs):
        if self.upload_files:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.upload_files.path))
        super(Free, self).delete(*args, **kargs)

    @property
    def created_string(self):
        time = timezone.now() - self.registered_date
        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.registered_date.date()
            return str(time.days) + '일 전'
        else:
            return False

    class Meta:
        db_table = '자유게시판'
        verbose_name = '자유게시판'
        verbose_name_plural = '자유게시판'


class Comment(models.Model):
    post = models.ForeignKey(Free, on_delete=models.CASCADE, verbose_name='게시글')
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='댓글작성자')
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE, verbose_name='댓글작성자')
    writer = models.CharField(max_length=17, null=True, verbose_name='댓글작성자')
    content = models.TextField(verbose_name='댓글내용')
    created = models.DateTimeField(auto_now_add=True, verbose_name='작성일')
    deleted = models.BooleanField(default=False, verbose_name='삭제여부')
    reply = models.IntegerField(verbose_name='답글위치', default=0)

    def __str__(self):
        return self.content

    @property
    def created_string(self):
        created_at = models.DateTimeField(auto_now_add=True)
        return created_at

    class Meta:
        db_table = '자유게시판 댓글'
        verbose_name = '자유게시판 댓글'
        verbose_name_plural = '자유게시판 댓글'

free/forms.py
from django import forms
from .models import Free


class FreeWriteForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(FreeWriteForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = '제목'
        self.fields['title'].widget.attrs.update({
            'placeholder': '제목을 입력해주세요.',
            'class': 'form-control',
            'id': 'form_title',
            'autofocus': True,
            'style': "width: 91%;"
        })
        self.fields['category'].label = '분류'
        self.fields['category'].widget.attrs.update({
            'class': 'custom-select custom-select-md',
            'style': "width: 8%; float:left; margin-right:1%"
        })

    class Meta:
        model = Free
        fields = ['category', 'title', 'content', 'upload_files']

free/views.py
from django.shortcuts import render, get_object_or_404, redirect
# from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import View, ListView, DetailView, FormView, CreateView
from .models import Free, Comment
from .decorators import login_message_required, admin_required
from django.db.models import Q
from django.contrib import messages
from django.urls import reverse
from .forms import FreeWriteForm
import mimetypes
from mimetypes import guess_type
import os
import re
from django.http import HttpResponse, HttpResponseRedirect, Http404
from urllib.parse import quote
import urllib
from django.conf import settings
import json
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder
from django.apps import apps

User = apps.get_model('users', 'User')


# 자유게시판 모두보기
class AllListView(ListView):
    model = Free
    paginate_by = 15
    template_name = 'free/free_list.html'
    context_object_name = 'free_list'

    def get_queryset(self):
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        free_list = Free.objects.order_by('-id')

        if search_keyword:
            if len(search_keyword) > 1:
                if search_type == 'all':
                    search_free_list = free_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword) | Q(
                            writer__username__icontains=search_keyword))
                elif search_type == 'title_content':
                    search_free_list = free_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword))
                elif search_type == 'title':
                    search_free_list = free_list.filter(title__icontains=search_keyword)
                elif search_type == 'content':
                    search_free_list = free_list.filter(content__icontains=search_keyword)
                elif search_type == 'writer':
                    search_free_list = free_list.filter(writer__username__icontains=search_keyword)

                return search_free_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return free_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')

        if len(search_keyword) > 1:
            context['q'] = search_keyword
        context['type'] = search_type

        return context


# 카테고리 자유만 보기
class FreeListView(AllListView):
    def get_queryset(self):
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        free_list = Free.objects.filter(category='자유').order_by('-id')

        if search_keyword:
            if len(search_keyword) > 1:
                if search_type == 'all':
                    search_free_list = free_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword) | Q(
                            writer__username__icontains=search_keyword))
                elif search_type == 'title_content':
                    search_free_list = free_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword))
                elif search_type == 'title':
                    search_free_list = free_list.filter(title__icontains=search_keyword)
                elif search_type == 'content':
                    search_free_list = free_list.filter(content__icontains=search_keyword)
                elif search_type == 'writer':
                    search_free_list = free_list.filter(writer__username__icontains=search_keyword)

                return search_free_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return free_list


# 카테고리 질문만 보기
class QuestionListView(AllListView):
    def get_queryset(self):
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        free_list = Free.objects.filter(category='질문').order_by('-id')

        if search_keyword:
            if len(search_keyword) > 1:
                if search_type == 'all':
                    search_free_list = free_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword) | Q(
                            writer__username__icontains=search_keyword))
                elif search_type == 'title_content':
                    search_free_list = free_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword))
                elif search_type == 'title':
                    search_free_list = free_list.filter(title__icontains=search_keyword)
                elif search_type == 'content':
                    search_free_list = free_list.filter(content__icontains=search_keyword)
                elif search_type == 'writer':
                    search_free_list = free_list.filter(writer__username__icontains=search_keyword)

                return search_free_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return free_list


# 카테고리 정보만 보기
class InformationListView(AllListView):
    def get_queryset(self):
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        free_list = Free.objects.filter(category='정보').order_by('-id')

        if search_keyword:
            if len(search_keyword) > 1:
                if search_type == 'all':
                    search_free_list = free_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword) | Q(
                            writer__username__icontains=search_keyword))
                elif search_type == 'title_content':
                    search_free_list = free_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword))
                elif search_type == 'title':
                    search_free_list = free_list.filter(title__icontains=search_keyword)
                elif search_type == 'content':
                    search_free_list = free_list.filter(content__icontains=search_keyword)
                elif search_type == 'writer':
                    search_free_list = free_list.filter(writer__username__icontains=search_keyword)

                return search_free_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return free_list


# 자유게시판 글 상세보기
# @login_message_required
def free_detail_view(request, pk):
    free = get_object_or_404(Free, pk=pk)
    comment = Comment.objects.filter(post=pk).order_by('created')
    comment_count = comment.exclude(deleted=True).count()
    reply = comment.exclude(reply='0')

    if request.user == free.writer:
        free_auth = True
    else:
        free_auth = False

    context = {
        'free': free,
        'free_auth': free_auth,
        'comments': comment,
        'comment_count': comment_count,
        'replys': reply,
    }
    return render(request, 'free/free_detail.html', context)


# 자유게시판 글 쓰기
@login_message_required
def free_write_view(request):
    if request.method == "POST":
        form = FreeWriteForm(request.POST, request.FILES)

        if form.is_valid():
            free = form.save(commit=False)

            if request.FILES:
                if 'upload_files' in request.FILES.keys():
                    free.filename = request.FILES['upload_files'].name

            free.save()
            return redirect('free:all_list')
    else:
        form = FreeWriteForm()
    return render(request, "free/free_write.html", {'form': form})


# 자유게시판 글 수정
@login_message_required
def free_edit_view(request, pk):
    free = Free.objects.get(id=pk)
    if request.method == "POST":
        if request.user.is_superuser:

            file_change_check = request.POST.get('fileChange', False)
            file_check = request.POST.get('upload_files-clear', False)

            if file_check or file_change_check:
                os.remove(os.path.join(settings.MEDIA_ROOT, free.upload_files.path))

            form = FreeWriteForm(request.POST, request.FILES, instance=free)
            if form.is_valid():
                free = form.save(commit=False)

                if request.FILES:
                    if 'upload_files' in request.FILES.keys():
                        free.filename = request.FILES['upload_files'].name

                free.save()
                messages.success(request, "수정되었습니다.")
                return redirect('/free/' + str(pk))
    else:
        free = Free.objects.get(id=pk)
        if request.user.is_superuser:
            form = FreeWriteForm(instance=free)
            context = {
                'form': form,
                'edit': '수정하기',
            }
            if free.filename and free.upload_files:
                context['filename'] = free.filename
                context['file_url'] = free.upload_files.url
            return render(request, "free/free_write.html", context)

free/templates/free/free_list.html
{% extends "users/main_base.html" %}
{% load humanize %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row mt-5">
        <div class="col-6">
            <h4 style="font-weight: bold;">자유게시판</h4>
            {% if q %}
            <h5 style="color: gray; font-weight: 550;"><i class="fas fa-search"></i>&nbsp;'{{ q }}' 검색 결과입니다.</h5>
            {% endif %}
        </div>
        <div class="col-6">
            <div class="dropdown" style="float:right; padding-top:3px; padding-right:8px;">
                <a class="dropdown-toggle mr-2" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false" style="font-size: 16px; color:black;">
                    분류별로 보기</a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'free:all_list' %}">전체보기</a>
                    <a class="dropdown-item" href="{% url 'free:free_list' %}">자유만 보기</a>
                    <a class="dropdown-item" href="{% url 'free:question_list' %}">질문만 보기</a>
                    <a class="dropdown-item" href="{% url 'free:information_list' %}">정보만 보기</a>
                </div>
            </div>
        </div>
    </div>
    <div>
        <table class="table table-sm table-hover">
            <thead style="border-top: 1px solid #dee2e6;">
                <tr class="text-center">
                    <th style="font-weight: bold; font-size: 16px;">번호</th>
                    <th style="font-weight: bold; font-size: 16px;">제목</th>
                    <th style="font-weight: bold; font-size: 16px;">작성자</th>
                    <th style="font-weight: bold; font-size: 16px;">등록일</th>
                    <th style="font-weight: bold; font-size: 16px;">조회수</th>
                </tr>
            </thead>
            <tbody>
                {% if free_list %}
                {% for free in free_list %}
                <tr class="text-center" style="cursor:pointer;" onclick="location.href='/free/{{ free.id }}/'">
                    <td style="font-weight: 500;">{{ free.id }}</td>
                    <td class="text-left" style="width:50%; font-weight: 600;">
                        {% if free.category == '자유' %}
                        <span class="badge badge-light">{{ free.category }}</span>&nbsp;
                        {% elif free.category == '질문' %}
                        <span class="badge badge-danger">{{ free.category }}</span>&nbsp;
                        {% elif free.category == '정보' %}
                        <span class="badge badge-info">{{ free.category }}</span>&nbsp;
                        {% endif %}
                        <!-- <a id="free-{{ free.id }}" href="{% url 'free:free_detail' free.id %}">{{ free.title|truncatechars:30 }}</a> -->
                        <a id="free-{{ free.id }}">{{ free.title|truncatechars:30 }}</a>
                        {% if free.comments %}
                        &nbsp;<span style="color:gray;">[{{ free.comments }}]</span>
                        {% endif %}
                    </td>
                    <td style="font-weight: 500;">{{ free.writer }}</td>
                    {% if free.created_string == False %}
                    <td style="font-weight: 500;">{{ free.registered_date|date:'m월 d일' }}</td>
                    {% else %}
                    <td style="font-weight: 500;">{{ free.created_string }}</td>
                    {% endif %}
                    <td style="font-weight: 500;">{{ free.hits }}</td>
                </tr>
                {% endfor %}
                {% else %}
                    {% if q %}
                    <tr class="text-center">
                        <td style="font-weight: bold; color:gray;" colspan="5">
                            <i class="fas fa-info-circle"></i>&nbsp;일치하는 검색 결과가 없습니다.
                        </td>
                    </tr>
                    {% else %}
                        <tr class="text-center">
                            <td style="font-weight: bold; color:gray;" colspan="5">
                                <i class="fas fa-info-circle"></i>&nbsp;작성된 게시글이 없습니다.
                            </td>
                        </tr>
                    {% endif %}
                {% endif %}
            </tbody>
        </table>
    </div>
    
    <div style="margin-top: 30px;">
        <form action="" method="GET">
            <div class="col">
                <div style="float: right;" class="form-row">
                    <div class="form-row">
                        <div class="col" style="margin-top: 10px;">
                            <select style="width: 6em;" class="custom-select custom-select-md" name="type">
                                <option value="all">전체</option>
                                <option value="title_content">제목+내용</option>
                                <option value="title">제목</option>
                                <option value="content">내용</option>
                                <option value="writer">작성자</option>
                            </select>
                        </div>
                        <div class="col" style="margin-top: 10px;">
                            <input type="text" name="q" value="{{ q }}" class="form-control form-control-md"
                                style="width: 15em;" placeholder="검색어를 입력해주세요.">
                        </div>
                        <div class="col">
                            <button class="btn btn-sm" type="submit" id="search_btn">검색</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <div>
            <div>
                <a href="{% url 'free:free_write' %}" id="write_btn" class="btn btn-sm">글쓰기</a>
            </div>
        </div>
        <br>
        <div class="col-md-offset-6">
            {% if is_paginated %}
            <!-- <ul class="pagination justify-content-center pagination-sm"> -->
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page_obj.previous_page_number }}"
                        tabindex="-1" style="font-size: 15px;">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" style="font-size: 15px;">이전</a>
                </li>
                {% endif %}

                {% for page in page_range %}
                <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
                    <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page }}" style="font-size: 15px;">{{ page }}</a>
                </li>
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link"
                        href="?type={{ type }}&q={{ q }}&page={{ page_obj.next_page_number }}" style="font-size: 15px;">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" style="font-size: 15px;">다음</a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>

<script type="text/javascript">
    target = window.location.search.split('&')[0].split('=')[1]
    var type = document.getElementsByTagName('option')
    for (var i = 0; i < 5; i++) {
        if (type[i].value === target) {
            type[i].setAttribute('selected', 'selected')
        }
    }
</script>
{% endblock %}

free/templates/free/free_write.html
{% extends "users/main_base.html" %}
{% load humanize %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block summernote %}
<link rel="stylesheet" href="{% static 'free/css/summernote.css' %}" type="text/css">
<script src="{% static 'free/js/summernote.js' %}"></script>
<script type="text/javascript" src="{% static 'free/js/summernote-ko-KR.js' %}"></script>
<script>
    $(document).ready(function () {
        $('#id_content').summernote({
            placeholder: '내용을 입력해주세요.',
            height: 500,
            minHeight: 500,
            maxHeight: 500,
            lang: 'ko-KR',
           
            toolbar: [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'help']]
            ]
        });
        $('p').css('margin-bottom','0')
        $('.note-resizebar').css('display','none');
    });
</script>
{% endblock %}

{% block contents %}
{% load static %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <h4 style="font-weight: bold;">자유게시판</h4>
        </div>
    </div>

    <div class="row-mt-5">
        <!--본문-->
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card" style="width: 100%;">
                <!--제목,분류,작성일-->
                <div class="card-header" style="padding: 0rem 0.2rem">
                    <div class="md-form form-group" style="margin-top: 8.5px;">
                        <div style="padding: 0 5.5px;">
                            {{ form.category }}
                            {{ form.title }}
                        </div>
                    </div>
                </div>
                    <!--내용-->
                    {{ form.content }}
            </div>
            
            <div class="card-footer" style="padding-left: 0px; margin-top:18px;">
                <div class="form-group">
                    <div class="col-sm-12">
                        {{ form.upload_files }}
                        <small id="help" class="form-text text-muted" style="margin-bottom: -15px;">
                            &nbsp;&nbsp;[파일 업로드]&nbsp;&nbsp;<i class="fas fa-upload"></i>&nbsp;10MB 이하의 파일만 첨부 가능합니다. 여러 파일은 압축해서 업로드해주세요.
                        </small>
                    </div>
                </div>
            </div>
            <div class="text-right" style="margin-top: 10px;">
                {% if edit %}
                <button type="submit" id="write" class="btn btn-sm">{{ edit }}</button>
                {% else %}
                <button type="submit" id="write" class="btn btn-sm">작성하기</button>
                {% endif %}
                <input type="checkbox" id="fileChangeCheck" name="fileChange" style="display: none;">
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    var checkUnload = true;
    $(window).on('beforeunload', function () {
        if (checkUnload) return "이 페이지를 벗어나면 작성된 내용은 저장되지 않습니다.";
    });
    $("#write").on("click", function () {
        checkUnload = false;
        $("submit").submit();
    });
</script>

{% if filename %}
<script type = "text/javascript">
    $('[href="{{ file_url }}"]').html("{{ filename }}");
    $('#upload_files-clear_id').css({opacity:'100', position:'relative', 'pointer-events':'auto'})

    $("#id_upload_files").change(function() {
        if ($('#id_upload_files').get(0).files.length == 1) {
            $(".col-sm-12").contents().get(0).nodeValue = '[첨부파일 변경 시 기존 파일은 삭제됩니다.]'
            $('#upload_files-clear_id').attr("checked", false)
            $('#upload_files-clear_id').prev().hide()
            $('#upload_files-clear_id').next().hide()
            $('#upload_files-clear_id').hide()
        }
    });

    $('#upload_files-clear_id').on('click', function(){
        if($(this).prop('checked')){
            $('#id_upload_files').hide()
            document.getElementById('id_upload_files').previousSibling.nodeValue = '[업로드 된 첨부파일을 삭제합니다.]'
        } else{
            $('#id_upload_files').show()
            document.getElementById('id_upload_files').previousSibling.nodeValue = '변경: '
        }
    });

    $('#write').click( function() {
        if($('#id_upload_files').get(0).files.length == 1){
            $('#fileChangeCheck').attr("checked",true)
        }
    });
</script>
{% endif %}
{% endblock %}