blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('tag/<str:slug>', views.tag_page),
    path('category/<str:slug>', views.category_page),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('blog_list/', views.PostList.as_view(), name='blog_list'),
]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/vote/', views.vote, name='vote'),
    path('<int:pk>/results/', views.results, name='results'),
]

django_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('blog/', include('blog.urls')),
    path("admin/", admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('single_pages.urls')),
    path('users/', include('users.urls')),
    path('notice/', include('notice.urls')),
    path('free/', include('free.urls')),
    path('anonymous/', include('anonymous.urls')),
    path('calender/', include('calender.urls')),
    path('about/', include('about.urls')),
    path('board/', include('board.urls')),



]




if settings.DEBUG:

    urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.contrib.auth.models import User
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.question_text}'

class VoteChoice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.choice_text}'

class UserVote(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    choices = models.ManyToManyField(VoteChoice)

    def __str__(self):
        return f"{self.user.username}\'s votes" if self.user else 'Anonymous votes'

board/forms.py
from django import forms
from .models import VoteChoice

class VoteForm(forms.Form):
    choices = forms.ModelMultipleChoiceField(
        queryset=VoteChoice.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

board/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Question, VoteChoice, UserVote
from .forms import VoteForm

def index(request):
    latest_question_list = Question.objects.order_by('-pk')
    return render(
        request,
        'board/index.html',
        {
            'latest_question_list': latest_question_list,
        }
    )

def detail(request, pk):
    question = get_object_or_404(Question, pk=pk)

    return render(
        request,
        'board/detail.html',
        {
            'question': question,
        }
    )

def vote(request, pk):
    question = get_object_or_404(Question, pk=pk)
    choices = question.votechoice_set.all()
    user_vote = UserVote.objects.filter(user=request.user, choices__question=question).first()

    if request.method == 'POST':
        form = VoteForm(request.POST)

        if form.is_valid():
            selected_choices = form.cleaned_data['choices']

            if user_vote:
                # 기존 투표를 수정
                user_vote.choices.clear()
            else:
                # 새로운 투표 생성
                user_vote = UserVote.objects.create(user=request.user)

            user_vote.choices.add(*selected_choices)

            return HttpResponseRedirect(reverse('board:results', args=(pk,)))
    else:
        # 투표한 경우 해당 선택지들을 미리 체크된 상태로 폼에 전달
        initial_data = {'choices': user_vote.choices.values_list('pk', flat=True)} if user_vote else None
        form = VoteForm(initial=initial_data)

    return render(request, 'board/detail.html', {'question': question, 'form': form, 'choices': choices})

def results(request, pk):
    question = get_object_or_404(Question, pk=pk)
    choices = question.votechoice_set.all()
    return render(request, 'board/results.html', {'question': question, 'choices': choices})

board/templates/board/detail.html
{% extends "users/main_base.html" %}
{% load static %}
{% block main_area %}
    <div class="d-flex justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="card" style="width: 24rem; height: 18rem; font-size: 16px">
            <div class="card-header">{{ question.question_text }}</div>
            <ul class="list-group list-group-flush" style="line-height: 4;">
                <li class="list-group-item">
                    <form action="{% url 'board:vote' question.id %}" method="post">
                        {% csrf_token %}

                        {% for choice in question.votechoice_set.all %}
                            <input type="checkbox" name="choices" id="choice{{ choice.id }}" value="{{ choice.id }}">
                            <label for="choice{{ choice.id }}">{{ choice.choice_text }}</label><br>
                        {% endfor %}

                        <button type="submit" class="btn btn-outline-danger">Vote</button>
                    </form>
                </li>
            </ul>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}

board/templates/board/index.html
{% extends "users/main_base.html" %}
{% load static %}
{% block main_area %}
<div class="home_bg">
    <div class="header">
        {% include 'blog/navbar.html' %}
    </div>

        <div class="d-flex justify-content-center align-items-center" style="min-height: 100vh;">
            <div class="card" style="width: 38rem; height: 18rem; font-size: 16px">
                <div class="card-header" style="font-size: 24px; background-color: #F6CEF5; color: #CC2EFA;">Latest Questions</div>
                <ul class="list-group list-group-flush" style="line-height: 4;">
                    {% for question in latest_question_list %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{% url 'board:detail' question.id %}">{{ question.question_text }}</a>
                            <span class="badge" style="color: #CC2EFA">{{ question.created_at }}</span>
                        </li>

                    {% endfor %}
                    </li>
                </ul>
            </div>
        </div>

</div>

{% include 'blog/footer.html' %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}

board/templates/board/results.html
{% extends "users/main_base.html" %}
{% load static %}
{% block main_area %}
<div class="home_bg">
    <div class="header">
        {% include 'blog/navbar.html' %}
    </div>

    <div class="d-flex justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="card align-items-center" style="width: 30rem; height: 10rem; font-size: 16px">
            <ul class="list-group list-group-flush" style="line-height: 4;">
                Thank you for voting "{{ question.question_text }}"
                {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }}: {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
                {% endfor %}
                <p><a href="{% url 'board:index' %}">Return to the index</a></p>
            </ul>
        </div>
    </div>
</div>

{% include 'blog/footer.html' %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}