blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('tag/<str:slug>', views.tag_page),
    path('category/<str:slug>', views.category_page),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('blog_list/', views.PostList.as_view(), name='blog_list'),
]

django_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('blog/', include('blog.urls')),
    path("admin/", admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('single_pages.urls')),
    path('users/', include('users.urls')),
    path('notice/', include('notice.urls')),
    path('free/', include('free.urls')),
    path('anonymous/', include('anonymous.urls')),
    path('calender/', include('calender.urls')),
    path('about/', include('about.urls')),
    path('board/', include('board.urls')),



]




if settings.DEBUG:

    urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib import messages
from django.shortcuts import redirect


app_name = 'notice'

def protected_file(request, path, document_root=None):
    messages.error(request, "접근 불가")
    return redirect('/')

urlpatterns = [
    path('', views.NoticeListView.as_view(), name='notice_list'),
    path('write/', views.notice_write_view, name='notice_write'),
    path('<int:pk>/', views.notice_detail_view, name='notice_detail'),
    path('<int:pk>/edit/', views.notice_edit_view, name='notice_edit'),
    path('<int:pk>/delete/', views.notice_delete_view, name='notice_delete'),
    path('download/<int:pk>', views.notice_download_view, name="notice_download"),
]

urlpatterns += static(settings.MEDIA_URL, protected_file, document_root=settings.MEDIA_ROOT)

notice/models.py
import os
from django.conf import settings
from django.db import models
from uuid import uuid4
from django.contrib.auth.models import User

from django.utils import timezone
from datetime import datetime



def get_file_path(instance, filename):
    ymd_path = datetime.now().strftime('%Y/%m/%d')
    uuid_name = uuid4().hex
    return '/'.join(['upload_file/', ymd_path, uuid_name])



class Notice(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='작성자', related_name='writer')
    title = models.CharField(max_length=128, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    hits = models.PositiveIntegerField(verbose_name='조회수', default=0)
    upload_images = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='이미지파일')
    upload_files = models.FileField(upload_to=get_file_path, null=True, blank=True, verbose_name='파일')
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')
    top_fixed = models.BooleanField(verbose_name='상단고정', default=False)
    filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')

    def __str__(self):
        return self.title


    def delete(self, *args, **kargs):
        if self.upload_files:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.upload_files.path))
        super(Notice, self).delete(*args, **kargs)

    class Meta:
        db_table = '공지사항'
        verbose_name = '공지사항'
        verbose_name_plural = '공지사항'

notice/forms.py
from django import forms
from .models import Notice



class NoticeWriteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(NoticeWriteForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = '제목'
        self.fields['title'].widget.attrs.update({
            'placeholder': '제목을 입력해주세요.',
            'class': 'form-control',
            'id': 'form_title',
            'autofocus': True,
        })

    class Meta:
        model = Notice
        fields = ['title', 'content', 'upload_files', 'top_fixed']

notice/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.generic import View, ListView, DetailView, FormView, CreateView
from .models import Notice
from django.db.models import Q
from django.contrib import messages
from django.urls import reverse
from .forms import NoticeWriteForm
import mimetypes
from mimetypes import guess_type
import os
import re
from django.http import HttpResponse, HttpResponseRedirect, Http404
from urllib.parse import quote
import urllib
from django.conf import settings
from django.apps import apps
from .decorators import login_message_required, admin_required

User = apps.get_model('users', 'User')




# 공지사항 리스트 뷰
class NoticeListView(ListView):
    model = Notice
    paginate_by = 15
    template_name = 'notice/notice_list.html'  # DEFAULT : <app_label>/<model_name>_list.html
    context_object_name = 'notice_list'  # DEFAULT : <app_label>_list

    def get_queryset(self):
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        notice_list = Notice.objects.order_by('-id')

        if search_keyword:
            if len(search_keyword) > 1:
                if search_type == 'all':
                    search_notice_list = notice_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword) | Q(
                            writer__username__icontains=search_keyword))
                elif search_type == 'title_content':
                    search_notice_list = notice_list.filter(
                        Q(title__icontains=search_keyword) | Q(content__icontains=search_keyword))
                elif search_type == 'title':
                    search_notice_list = notice_list.filter(title__icontains=search_keyword)
                elif search_type == 'content':
                    search_notice_list = notice_list.filter(content__icontains=search_keyword)
                elif search_type == 'writer':
                    search_notice_list = notice_list.filter(writer__user_id__icontains=search_keyword)

                return search_notice_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return notice_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        notice_fixed = Notice.objects.filter(top_fixed=True).order_by('-registered_date')

        if len(search_keyword) > 1:
            context['q'] = search_keyword
        context['type'] = search_type
        context['notice_fixed'] = notice_fixed

        return context


# 공지사항 게시글 보기
# @login_message_required
def notice_detail_view(request, pk):
    notice = get_object_or_404(Notice, pk=pk)


    if request.user == notice.writer:
        notice_auth = True
    else:
        notice_auth = False

    context = {
        'notice': notice,
        'notice_auth': notice_auth,
    }

    return render(request, 'notice/notice_detail.html', context)


# 공지사항 글쓰기
@login_message_required
@admin_required
def notice_write_view(request):
    if request.method == "POST":
        form = NoticeWriteForm(request.POST, request.FILES)

        if form.is_valid():
            notice = form.save(commit=False)
            if request.FILES:
                if 'upload_files' in request.FILES.keys():
                    notice.filename = request.FILES['upload_files'].name
            notice.save()
            return redirect('notice:notice_list')
    else:
        form = NoticeWriteForm()
    return render(request, "notice/notice_write.html", {'form': form})


# 공지사항 게시글 수정
@login_message_required
def notice_edit_view(request, pk):
    notice = Notice.objects.get(id=pk)

    if request.method == "POST":
        if request.user.is_superuser:
            file_change_check = request.POST.get('fileChange', False)
            file_check = request.POST.get('upload_files-clear', False)

            if file_check or file_change_check:
                os.remove(os.path.join(settings.MEDIA_ROOT, notice.upload_files.path))

            form = NoticeWriteForm(request.POST, request.FILES, instance=notice)
            if form.is_valid():
                notice = form.save(commit=False)
                if request.FILES:
                    if 'upload_files' in request.FILES.keys():
                        notice.filename = request.FILES['upload_files'].name
                notice.save()
                messages.success(request, "수정되었습니다.")
                return redirect('/notice/' + str(pk))
    else:
        notice = Notice.objects.get(id=pk)
        if request.user.is_superuser:
            form = NoticeWriteForm(instance=notice)
            context = {
                'form': form,
                'edit': '수정하기',
            }
            if notice.filename and notice.upload_files:
                context['filename'] = notice.filename
                context['file_url'] = notice.upload_files.url
            return render(request, "notice/notice_write.html", context)
        else:
            messages.error(request, "본인 게시글이 아닙니다.")
            return redirect('/notice/' + str(pk))


# 공지사항 게시글 삭제
@login_message_required
def notice_delete_view(request, pk):
    notice = Notice.objects.get(id=pk)
    if request.user.is_superuser:
        notice.delete()
        messages.success(request, "삭제되었습니다.")
        return redirect('/notice/')
    else:
        messages.error(request, "본인 게시글이 아닙니다.")
        return redirect('/notice/' + str(pk))


# 공지사항 게시글 첨부파일 다운로드 한글명 인코딩
@login_message_required
def notice_download_view(request, pk):
    notice = get_object_or_404(Notice, pk=pk)
    url = notice.upload_files.url[1:]
    print(type(url))
    print(url)
    file_url = urllib.parse.unquote(url)

    if os.path.exists(file_url):
        with open(file_url, 'rb') as fh:
            quote_file_url = urllib.parse.quote(notice.filename.encode('utf-8'))
            response = HttpResponse(fh.read(), content_type=mimetypes.guess_type(file_url)[0])
            response['Content-Disposition'] = 'attachment;filename*=UTF-8\'\'%s' % quote_file_url
            return response
        raise Http404

notice/templates/notice/notice_detail.html
{% extends "users/main_base.html" %}
{% load humanize %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block contents %}
<br><br><br>
<div class="container">
    <div class="row-mt-5">
        <div class="col-12">
            <!--본문-->
            <div class="card" style="width: 100%;">
                <!--제목,분류,작성일-->
                <div class="card-header">
                    <strong style="font-size: 18px;">{{ notice.title }}</strong>&nbsp;&nbsp;<span
                        style="font-size: 18px; color: gray;">[공지사항]</span>
                    <span style="float:right;">{{ notice.registered_date|date:'Y.m.d. H:i' }}</span>
                </div>
                <div class="card-body" style="min-height: 400px; color:black;">
                    <!--작성자, 조회수-->
                    <div>
                        <span><i class="fas fa-user-edit"></i>&nbsp;작성자 : {{ notice.writer }}</span>
                        <span style="float:right;">조회수 : {{ notice.hits }}</span>
                    </div>
                    <hr>
                    {% if notice.upload_files %}
                    <div class="col-12 text-right">
                        <span style="color: gray;">첨부파일 :&nbsp;</span>
                        <a id="id_uploaded_file" href="{% url 'notice:notice_download' notice.id %}">{{ notice.filename|truncatechars:25 }}</a>
                    </div>
                    {% endif %}
                    <!--내용-->
                    <div>
                        {{ notice.content | safe }}
                    </div>
                </div>
            </div>
            <br>
            <div class="text-right" style="margin-top:-15px;">
                {% if user.is_superuser %}
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/notice/{{ notice.id }}/edit/'">수정
                </button>
                <button class="btn btn-sm" id="detail_btn" data-toggle="modal" data-target="#delete_modal">삭제</button>
                <!-- <button class="btn btn-md btn-dark" onclick="location.href='/notice/{{ notice.id }}/delete/'">삭제</button> -->
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/notice/'">목록으로</button>
                {% else %}
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/notice/'">목록으로</button>
                {% endif %}
            </div>
        </div>
    </div>

    <div id="delete_modal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">삭제경고</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>게시글을 삭제하시겠습니까?</p>
                </div>
                <div class="modal-footer">
                    <button onclick="delete_modal()" type="button" class="btn btn-dark">삭제하기</button>
                    <button type="button" class="btn btn-light" data-dismiss="modal">취소하기</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('img').css('width', '100%');
    });

    function delete_modal() {
        location.replace('/notice/{{ notice.id }}/delete/');
    }
</script>

{% endblock %}

notice/templates/notice/notice_list.html
{% extends "users/main_base.html" %}
{% load humanize %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <h4 style="font-weight: bold;">공지사항</h4>
            {% if q %}
            <h5 style="color: gray; font-weight: 550;"><i class="fas fa-search"></i>&nbsp;'{{ q }}' 검색 결과입니다.</h5>
            {% endif %}
        </div>
    </div>
    <div>
        <table class="table table-sm table-hover">
            <thead style="border-top: 1px solid #dee2e6;">
                <tr class="text-center">
                    <th style="font-weight: bold; font-size: 16px;">번호</th>
                    <th style="font-weight: bold; font-size: 16px;">제목</th>
                    <th style="font-weight: bold; font-size: 16px;">작성자</th>
                    <th style="font-weight: bold; font-size: 16px;">등록일</th>
                    <th style="font-weight: bold; font-size: 16px;">조회수</th>
                </tr>
                {% if q %}
                {% else %}
                {% if notice_fixed %}
                {% for notice in notice_fixed %}
                <tr class="table-secondary text-center" style="font-weight: bold; cursor:pointer;" onclick="location.href='/notice/{{ notice.id }}/'">
                    <td>{{ notice.id }}</td>
                    <td class="text-left" style="width:50%"><a id="notice-{{ notice.id }}"><i class="fas fa-bullhorn"></i>&nbsp;&nbsp;&nbsp;{{ notice.title|truncatechars:30 }}</a></td>
                    <td>{{ notice.writer }}</td>
                    <td>{{ notice.registered_date|date:'Y. m. d' }}</td>
                    <td>{{ notice.hits }}</td>
                </tr>
                {% endfor %}
                {% endif %}
                {% endif %}
            </thead>
            <tbody>
                {% if notice_list %}
                {% for notice in notice_list %}
                <tr class="text-center" style="cursor:pointer;" onclick="location.href='/notice/{{ notice.id }}/'">
                    <td style="font-weight: 500;">{{ notice.id }}</td>
                    <td class="text-left" style="width:50%; font-weight: 600;"><a id="notice-{{ notice.id }}">{{ notice.title|truncatechars:30 }}</a></td>
                    <td style="font-weight: 500;">{{ notice.writer }}</td>
                    <td style="font-weight: 500;">{{ notice.registered_date|date:'Y. m. d' }}</td>
                    <td style="font-weight: 500;">{{ notice.hits }}</td>
                </tr>
                {% endfor %}
                {% else %}
                    {% if q %}
                    <tr class="text-center">
                        <td style="font-weight: bold; color:gray;" colspan="5">
                            <i class="fas fa-info-circle"></i>&nbsp;일치하는 검색 결과가 없습니다.
                        </td>
                    </tr>
                    {% else %}
                        <tr class="text-center">
                            <td style="font-weight: bold; color:gray;" colspan="5">
                                <i class="fas fa-info-circle"></i>&nbsp;작성된 게시글이 없습니다.
                            </td>
                        </tr>
                    {% endif %}
                {% endif %}
            </tbody>
        </table>
    </div>

    <div style="margin-top: 30px;">
        <form action="" method="GET">
            <div class="col">
                <div style="float: right;" class="form-row">
                    <div class="form-row">
                        <div class="col" style="margin-top: 10px;">
                            <select style="width: 6em;" class="custom-select custom-select-md" name="type">
                                <option value="all">전체</option>
                                <option value="title_content">제목+내용</option>
                                <option value="title">제목</option>
                                <option value="content">내용</option>
                                <option value="writer">작성자</option>
                            </select>
                        </div>
                        <div class="col" style="margin-top: 10px;">
                            <input type="text" name="q" value="{{ q }}" class="form-control form-control-md"
                                style="width: 15em;" placeholder="검색어를 입력해주세요.">
                        </div>
                        <div class="col">
                            <!-- <button class="btn btn-md btn-outline-dark" type="submit">검색</button> -->
                            <button class="btn btn-sm" type="submit" id="search_btn">검색</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        {% if user.is_superuser %}
        <div>
            <div>
                <a href="{% url 'notice:notice_write' %}" id="write_btn" class="btn btn-sm">글쓰기</a>
            </div>
        </div>
        <br>
        {% else %}
        <br><br><br>
        {% endif %}
        <div class="col-md-offset-6">
            {% if is_paginated %}
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page_obj.previous_page_number }}"
                        tabindex="-1" style="font-size: 15px;">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" style="font-size: 15px;">이전</a>
                </li>
                {% endif %}

                {% for page in page_range %}
                <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
                    <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page }}" style="font-size: 15px;">{{ page }}</a>
                </li>
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link"
                        href="?type={{ type }}&q={{ q }}&page={{ page_obj.next_page_number }}" style="font-size: 15px;">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" style="font-size: 15px;">다음</a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>

<script type="text/javascript">
    target = window.location.search.split('&')[0].split('=')[1]
    var type = document.getElementsByTagName('option')
    for (var i = 0; i < 5; i++) {
        if (type[i].value === target) {
            type[i].setAttribute('selected', 'selected')
        }
    }
</script>
{% endblock %}

notice/templates/notice/notice_write.html
{% extends "users/main_base.html" %}
{% load humanize %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block summernote %}

<link rel="stylesheet" href="{% static 'free/css/summernote.css' %}" type="text/css">
<script src="{% static 'free/js/summernote.js' %}"></script>

<script type="text/javascript" src="free/js/summernote-ko-KR.js"></script>
<script>
    $(document).ready(function () {
        $('#id_content').summernote({
            placeholder: '내용을 입력해주세요.',
            height: 500,
            minHeight: 500,
            maxHeight: 500,
            lang: 'ko-KR',
           
            toolbar: [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'help']]
            ]
        });
        $('p').css('margin-bottom','0')
        $('.note-resizebar').css('display','none');
    });
</script>
<!-- CheckBoxCSS -->
<link rel="stylesheet" href="{% static 'users/css/checkbox.css' %}" type="text/css">
{% endblock %}

{% block contents %}
{% load static %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <h4 style="font-weight: bold;">공지사항</h4>
        </div>
    </div>

    <div class="row-mt-5">
        <!--본문-->
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card" style="width: 100%;">
                <!--제목,분류,작성일-->
                <div class="card-header" style="padding: 0rem 0.8rem">
                    <div class="md-form form-group" style="margin-top: 8.5px;">
                        <div style="padding: 0 5.5px;">
                            {{ form.title }}
                        </div>
                    </div>
                </div>
                <div>
                    <!--내용-->
                    {{ form.content }}
                </div>
            </div>
            
            <div class="card-footer" style="padding-left: 0px; margin-top:18px;">
                <div class="form-group">
                    <div class="col-sm-12">
                        {{ form.upload_files }}
                        <small id="help" class="form-text text-muted" style="margin-bottom: -15px;">
                            &nbsp;&nbsp;[파일 업로드]&nbsp;&nbsp;<i class="fas fa-upload"></i>&nbsp;10MB 이하의 파일만 첨부 가능합니다. 여러 파일은 압축해서 업로드해주세요.
                        </small>
                    </div>
                </div>
            </div>
            <div class="text-right" style="margin-top: 10px;">
                <label>
                    {{ form.top_fixed }}
                    <span style="padding-bottom: 35px; color:black; font-weight: bold;">상단에 표시하기</span>
                </label>
                {% if edit %}
                <button type="submit" id="write" class="btn btn-sm">{{ edit }}</button>
                {% else %}
                <button type="submit" id="write" class="btn btn-sm">작성하기</button>
                {% endif %}
                <input type="checkbox" id="fileChangeCheck" name="fileChange" style="display: none;">
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    var checkUnload = true;
    $(window).on('beforeunload', function () {
        if (checkUnload) return "이 페이지를 벗어나면 작성된 내용은 저장되지 않습니다.";
    });
    $("#write").on("click", function () {
        checkUnload = false;
        $("submit").submit();
    });

</script>

{% if filename %}
<script type = "text/javascript">
    $('[href="{{ file_url }}"]').html("{{ filename }}");
    $('#upload_files-clear_id').css({opacity:'100', position:'relative', 'pointer-events':'auto'})

    $("#id_upload_files").change(function() {
        if ($('#id_upload_files').get(0).files.length == 1) {
            $(".col-sm-12").contents().get(0).nodeValue = '[첨부파일 변경 시 기존 파일은 삭제됩니다.]'
            $('#upload_files-clear_id').attr("checked", false)
            $('#upload_files-clear_id').prev().hide()
            $('#upload_files-clear_id').next().hide()
            $('#upload_files-clear_id').hide()
        }
    });



    $('#upload_files-clear_id').on('click', function(){
        if($(this).prop('checked')){
            $('#id_upload_files').hide()
            document.getElementById('id_upload_files').previousSibling.nodeValue = '[업로드 된 첨부파일을 삭제합니다.]'
        } else{
            $('#id_upload_files').show()
            document.getElementById('id_upload_files').previousSibling.nodeValue = '변경: '
        }
    });

    $('#write').click( function() {
        if($('#id_upload_files').get(0).files.length == 1){
            $('#fileChangeCheck').attr("checked",true)
        }
    });
</script>
{% endif %}

{% endblock %}