about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('', views.about_us, name='pitapat'),
    path('organization/', views.organization_view, name='organization'),
]

blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('tag/<str:slug>', views.tag_page),
    path('category/<str:slug>', views.category_page),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('blog_list/', views.PostList.as_view(), name='blog_list'),
]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/vote/', views.vote, name='vote'),
    path('<int:pk>/results/', views.results, name='results'),
]

django_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('blog/', include('blog.urls')),
    path("admin/", admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('single_pages.urls')),
    path('users/', include('users.urls')),
    path('notice/', include('notice.urls')),
    path('free/', include('free.urls')),
    path('anonymous/', include('anonymous.urls')),
    path('calender/', include('calender.urls')),
    path('about/', include('about.urls')),
    path('board/', include('board.urls')),



]




if settings.DEBUG:

    urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

free/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib import messages
from django.shortcuts import redirect


app_name = 'free'

def protected_file(request, path, document_root=None):
    messages.error(request, "접근 불가")
    return redirect('/')

urlpatterns = [
    path('all_list', views.AllListView.as_view(), name='all_list'),
    path('free/', views.FreeListView.as_view(), name='free_list'),
    path('question/', views.QuestionListView.as_view(), name='question_list'),
    path('information/', views.InformationListView.as_view(), name='information_list'),

    path('write/', views.free_write_view, name='free_write'),
    path('<int:pk>/', views.free_detail_view, name='free_detail'),
    path('<int:pk>/edit/', views.free_edit_view, name='free_edit'),
    path('<int:pk>/delete/', views.free_delete_view, name='free_delete'),
    path('download/<int:pk>', views.free_download_view, name="free_download"),

    path('<int:pk>/comment/write/', views.comment_write_view, name='comment_write'),
    path('<int:pk>/comment/delete/', views.comment_delete_view, name='comment_delete'),
]

urlpatterns += static(settings.MEDIA_URL, protected_file, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib import messages
from django.shortcuts import redirect


app_name = 'notice'

def protected_file(request, path, document_root=None):
    messages.error(request, "접근 불가")
    return redirect('/')

urlpatterns = [
    path('', views.NoticeListView.as_view(), name='notice_list'),
    path('write/', views.notice_write_view, name='notice_write'),
    path('<int:pk>/', views.notice_detail_view, name='notice_detail'),
    path('<int:pk>/edit/', views.notice_edit_view, name='notice_edit'),
    path('<int:pk>/delete/', views.notice_delete_view, name='notice_delete'),
    path('download/<int:pk>', views.notice_download_view, name="notice_download"),
]

urlpatterns += static(settings.MEDIA_URL, protected_file, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [

    path('main/', views.main_view, name='main'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('agreement/', views.AgreementView.as_view(), name='agreement'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('registerauth/', views.register_success, name='register_success'),
    path('activate/<str:uid64>/<str:token>/', views.activate, name='activate'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/post', views.profile_post_view, name='profile_post'),
    path('profile/comment', views.profile_comment_view, name='profile_comment'),
    path('profile/update/', views.profile_update_view, name='profile_update'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, Group, Permission
from .choice import *

class UserManager(BaseUserManager):

    def create_user(self, user_id, password, email, hp, name, student_id, grade, department, circles, auth,
                    **extra_fields):
        if not user_id:
            raise ValueError('user_id Required!')

        user = self.model(
            user_id=user_id,
            email=email,
            hp=hp,
            name=name,
            student_id=student_id,
            grade=grade,
            department=department,
            circles=circles,
            auth=auth,
            **extra_fields
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, user_id, password, email=None, hp=None, name=None, student_id=None, grade=None, department=None, circles=None, auth=None):
        user = self.create_user(user_id, password, email, hp, name, student_id, grade, department, circles, auth)

        user.is_superuser = True
        user.is_staff = True
        user.is_admin = True
        user.level = 0

        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    objects = UserManager()

    user_id = models.CharField(max_length=17, verbose_name="아이디", unique=True)
    password = models.CharField(max_length=256, verbose_name="비밀번호")
    email = models.EmailField(max_length=128, verbose_name="이메일", null=True, unique=True)
    hp = models.IntegerField(verbose_name="핸드폰번호", null=True, unique=True)
    name = models.CharField(max_length=8, verbose_name="이름", null=True)
    student_id = models.IntegerField(verbose_name="학번", null=True)
    grade = models.CharField(choices=GRADE_CHOICES, max_length=18, verbose_name="학년", null=True)
    # level = models.CharField(choices=LEVEL_CHOICES, max_length=18, verbose_name="등급", default=3)
    # circles = models.CharField(choices=CIRCLES_CHOICES, max_length=18, verbose_name="동아리", null=True)
    department = models.CharField(choices=DEPARTMENT_CHOICES, max_length=24, verbose_name="학과", null=True)
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name='가입일', null=True, blank=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'user_id'

    def __str__(self):
        return self.user_id

    class Meta:
        db_table = "회원목록"
        verbose_name = "사용자"
        verbose_name_plural = "사용자"

    groups = models.ManyToManyField(
        Group,
        verbose_name=('groups'),
        blank=True,
        help_text=('The groups this user belongs to.'),
        related_name='user_groups',  # 수정된 부분
        related_query_name='user',
    )
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name=('user permissions'),
        blank=True,
        help_text=('Specific permissions for this user.'),
        related_name='user_permissions',  # 수정된 부분
        related_query_name='user',
    )

users/views.py
from django.conf import settings
from django.apps import apps
from django.utils.datastructures import MultiValueDictKeyError
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# from .decorators import login_message_required, admin_required, logout_message_required
# from .decorators import admin_required, logout_message_required
from .decorators import login_message_required, admin_required
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, FormView, TemplateView
from django.views.generic import View
from .models import User

from .forms import RegisterForm, LoginForm, CustomUserChangeForm
from django.http import HttpResponse
import json
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder
from .helper import send_mail, email_auth_num
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, Http404
from django.forms.utils import ErrorList
from django.views.decorators.http import require_GET, require_POST
from django.core.exceptions import PermissionDenied

from django.apps import apps

# from .views import RegisterView


from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.tokens import default_token_generator
from datetime import datetime
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate, login

# from .forms import CsRegisterForm


Notice = apps.get_model('notice', 'Notice')
Free = apps.get_model('free', 'Free')
Comment = apps.get_model('free', 'Comment')
Anonymous = apps.get_model('anonymous', 'Anonymous')
AnonymousComment = apps.get_model('anonymous', 'AnonymousComment')
Calender = apps.get_model('calender', 'Calender')






# def index(request):
    # return render(request, 'users/main.html')


# 메인화면(로그인 후)
# @login_message_required
def main_view(request):
    notice_list = Notice.objects.order_by('-id')[:5]
    # calender_property = [x.event_id for x in Calender.objects.all() if x.d_day == False]
    calender_property = Calender.objects.filter(all_day=True)
    calendar_list = Calender.objects.exclude(event_id__in=calender_property).order_by('start_date')[:5]

    # calendar_list = Calender.objects.exclude(event_id__in=calender_property).order_by('start_date')[:5]
    free_list = Free.objects.filter(category='정보').order_by('-id')[:5]
    anonymous_list = sorted(Anonymous.objects.all(), key=lambda t: t.like_count, reverse=True)[:5]

    context = {
        'notice_list': notice_list,
        'calendar_list': calendar_list,
        'free_list': free_list,
        'anonymous_list': anonymous_list,
    }
    return render(request, 'users/main.html', context)


# 로그인
# @method_decorator(logout_message_required, name='dispatch')
class LoginView(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = '/users/main/'

    def form_valid(self, form):
        user_id = form.cleaned_data.get("user")
        password = form.cleaned_data.get("password")

        user = authenticate(self.request, username=user_id, password=password)
        if user is not None:
            self.request.session['user'] = user
            login(self.request, user)

            # Session Maintain Test

            remember_session = self.request.POST.get('remember_session', False)
            if remember_session:
                settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = False

            try:
                remember_session = self.request.POST['remember_session']
                if remember_session:
                    settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = False
            except MultiValueDictKeyError:
                settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = True

        return super().form_valid(form)


# 로그아웃
def logout_view(request):
    logout(request)
    return redirect('/')


# 회원가입 약관동의
# @method_decorator(logout_message_required, name='dispatch')
class AgreementView(View):
    def get(self, request, *args, **kwargs):
        request.session['agreement'] = False
        return render(request, 'users/agreement.html')

    def post(self, request, *args, **kwarg):
        if request.POST.get('agreement1', False) and request.POST.get('agreement2', False):
            request.session['agreement'] = True
            if request.POST.get('csregister') == 'csregister':
                return redirect('/users/csregister/')
            else:
                return redirect('/users/register/')
        else:
            messages.info(request, "약관에 모두 동의해주세요.")
            return render(request, 'users/agreement.html')


# 회원가입 인증메일 발송 안내 창
def register_success(request):
    if not request.session.get('register_auth', False):
        raise PermissionDenied
    request.session['register_auth'] = False

    return render(request, 'users/register_success.html')


# 회원가입
class RegisterView(CreateView):
    model = User
    template_name = 'users/register.html'
    form_class = RegisterForm

    def get(self, request, *args, **kwargs):
        if not request.session.get('agreement', False):
            raise PermissionDenied
        request.session['agreement'] = False

        url = settings.LOGIN_REDIRECT_URL
        if request.user.is_authenticated:
            return HttpResponseRedirect(url)
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        # messages.success(self.request, "회원가입 성공.")
        self.request.session['register_auth'] = True
        messages.success(self.request, '회원님의 입력한 Email 주소로 인증 메일이 발송되었습니다. 인증 후 로그인이 가능합니다.')
        return settings.LOGIN_URL
        # return reverse('users:register_success')

    def form_valid(self, form):
        self.object = form.save()

        send_mail(
            '[Pit A Pat] {}님의 회원가입 인증메일 입니다.'.format(self.object.user_id),
            [self.object.email],
            html=render_to_string('users/register_email.html', {
                'user': self.object,
                'uid': urlsafe_base64_encode(force_bytes(self.object.pk)).encode().decode(),
                'domain': self.request.META['HTTP_HOST'],
                'token': default_token_generator.make_token(self.object),
            }),
        )

        return redirect(self.get_success_url())


def activate(request, uid64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uid64))
        current_user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
        messages.error(request, '메일 인증에 실패했습니다.')
        return redirect('users:login')

    if default_token_generator.check_token(current_user, token):
        current_user.is_active = True
        current_user.save()

        messages.info(request, '메일 인증이 완료 되었습니다. 회원가입을 축하드립니다!')
        return redirect('users:login')

    messages.error(request, '메일 인증에 실패했습니다.')
    return redirect('users:login')


# 프로필 보기
# @login_message_required
def profile_view(request):
    if request.method == 'GET':
        return render(request, 'users/profile.html')


# 프로필 수정
# @login_message_required
def profile_update_view(request):
    if request.method == 'POST':

        user_change_form = CustomUserChangeForm(request.POST, instance=request.user)

        if user_change_form.is_valid():
            user_change_form.save()
            messages.success(request, '회원정보가 수정되었습니다.')
            return render(request, 'users/profile.html')
    else:

        user_change_form = CustomUserChangeForm(instance=request.user)

        return render(request, 'users/profile_update.html', {'user_change_form': user_change_form})




# 내가 쓴 글 보기
# @login_message_required
@require_GET
def profile_post_view(request):
    free_list = Free.objects.filter(writer=request.user.id).order_by('-registered_date')
    anonymous_list = Anonymous.objects.filter(writer=request.user.id).order_by('-registered_date')
    context = {
        'free_list': free_list,
        'anonymous_list': anonymous_list,
    }
    if request.user.is_superuser:
        notice_list = Notice.objects.filter(writer=request.user.id).order_by('-registered_date')
        context['notice_list'] = notice_list

    return render(request, 'users/profile_post.html', context)


# 댓글 단 글 보기
# @login_message_required
@require_GET
def profile_comment_view(request):
    comment_list = Comment.objects.select_related('post').filter(writer=request.user).exclude(deleted=True).order_by(
        '-created')
    anonymous_comment_list = AnonymousComment.objects.select_related('post').filter(writer=request.user).exclude(
        deleted=True).order_by('-created')
    context = {
        'comment_list': comment_list,
        'anonymous_comment_list': anonymous_comment_list,
    }
    return render(request, 'users/profile_comment.html', context)

users/templates/users/login.html
{% extends "users/user_base.html" %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=480, user-scalable=yes">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row justify-content-md-center">
        <div style="position: absolute; top: 40%; height: 476.06px; margin-top: -238.03px;">
            <div class="card" style="width: 30rem;">
                <div class="card-body">
                    <div class="text-center">
                        <img src="{% static 'users/img/logo2.jpg' %}" style="width:60%; margin:30px;">
                    </div>

                    <form method="POST" action="." novalidate>
                        {% csrf_token %}

                        <div class="mb-4 md-form">
                            <label name="label_user_id" for="{{ form.user_id.id_for_label }}"><i class="fas fa-user"></i>&nbsp;&nbsp;{{ form.user_id.label }}</label>
                            {{ form.user_id }}
                            <script type="text/javascript">
                                if (document.getElementsByName('user_id')[0].value != '') {
                                    document.getElementsByName('label_user_id')[0].setAttribute('class', 'active');
                                }
                            </script>
                            {% if form.user_id.errors %}
                            <script type="text/javascript">
                                document.getElementsByName('user_id')[0].setAttribute('class',
                                    'form-control is-invalid')
                            </script>
                            {% for error in form.user_id.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                            {% endfor %}
                            {% endif %}
                        </div>

                        <div class="mb-4 md-form">
                            <label for="{{ form.password.id_for_label }}"><i class="fas fa-lock"></i>&nbsp;&nbsp;{{ form.password.label }}</label>
                            {{ form.password }}

                            {% if form.password.errors %}
                            <script type="text/javascript">
                                document.getElementsByName('password')[0].setAttribute('class', 'form-control is-invalid')
                            </script>
                            {% for error in form.password.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                            {% endfor %}
                            {% endif %}
                        </div>
                        <label>
                            <input type="checkbox" name="remember_session"/>
                            <span style="padding-bottom: 35px;">로그인 상태 유지</span>
                        </label>
                        <br>
                        <button type="submit" style="opacity: 90%; font-size: 16px; margin-top: -5px;" class="btn btn-purple btn-lg btn-block">로그인</button>
                    </form>
                    <div style="text-align: center;">&middot;
                        <a style="color:gray; font-size: 14px;" href="{% url 'users:agreement' %}">회원가입</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/profile.html
{% extends "users/main_base.html" %}

{% block mobileView %}
<meta name="viewport" content="width=550, user-scalable=yes">
{% endblock %}

{% block contents %}
<div class="container">
    <div style="margin-top: 5rem !important;">
        <div class="col-12">

            <div class="row justify-content-center">
                <div class="card">
                    <div class="card-header" style="padding-bottom:8px;">
                        <strong style="font-size: 18px;"><i class="fas fa-user-cog"></i>&nbsp;&nbsp;내 정보</strong>
                    </div>
                    <div class="card-body">
                        <table style="color:black; margin-left:10px;">
                            <tr>
                                <td class="profile_title">아이디</td>
                                <td class="profile_content">{{ user.user_id }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">이메일</td>
                                <td class="profile_content">{{ user.email }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">이름</td>
                                <td class="profile_content">{{ user.name }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">연락처</td>
                                <td class="profile_content">0{{ user.hp }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">학번</td>
                                <td class="profile_content">{{ user.student_id|default:'작성안함' }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">학년</td>
                                <td class="profile_content">{{ user.grade|default:'선택안함' }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">학과</td>
                                <td class="profile_content">{{ user.department|default:'선택안함' }}</td>
                            </tr>
                        </table>

                        <hr>
                        <div style="text-align: center;">
<!--                            <a href="{% url 'users:profile_update' %}" style="color:rgba(93, 15, 92, 0.95); font-size:15px;"><i class="fas fa-user-edit"></i>&nbsp;내정보수정</a>&nbsp;&middot;&nbsp;-->
                             <br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/register_email.html
{% autoescape off %}
<!DOCTYPE html>
<html>
<body>
    <div style="width:100%;min-width:100%;height:100%;">
        <div style="padding: 70px 0; background: #f7f8f9;">
            <div style="margin: 0 auto; width: 600px; color: #000;">
                <div style="padding: 30px 90px; text-align: center; border: 1px solid #dfdfdf; background: #fff;">
                    <h3 style="margin-bottom: 35px; font-size: 30px; font-weight: 600;">회원가입 이메일 인증 발송</h3>
                    <div style="padding: 10px 0 20px; border-top: 1px solid rgb(172, 172, 172);">
                        <p style="font-size: 14px; font-weight: 600; line-height: 20px;">Pit A Pat 홈페이지 회원가입을 축하드립니다.<br>아래 링크를 클릭하여 로그인 해주시기 바랍니다.</p>
                    </div>
                    <div style="padding: 20px 30px; background: #f7f8f9;"><a style="font-size: 18px; font-weight: bold;" href="http://{{ domain }}{% url 'users:activate' uid64=uid token=token %}">인증하기</a></div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
{% endautoescape %}

users/templates/users/sidebar.html
{% load socialaccount %}

<nav id="sidebar">
    <div id="side_hide">
        <div style="position:fixed; left: 273px; z-index:3;">
            <div id="sidebarCollapseHide" onclick="hide()"
                 style="margin-top: 15px; margin-right:15px; margin-bottom: -30px; cursor: pointer;">
                <i class="fa fa-chevron-left fa-lg"></i>
            </div>
        </div>
    </div>
    <div class="p-4 pt-5" style="position: fixed; width:300px;">
        {% if user.is_authenticated %}

        <span style="font-size: 22px;">{{ user.username }}</span> 님 환영합니다.
        <a href="{% url 'users:logout' %}" style="margin-left:33px;">로그아웃</a>
        <br>
        {% else %}
        <p>이 유저는 로그아웃 되어 있습니다.</p>

<!--        <li class="nav-item">-->
                    <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal" style="color: #ffffff;">Log In</a>
<!--        </li>&nbsp;&middot;-->
<!--        <a href="{% url 'users:agreement' %}">회원가입</a>-->
        <br>
        {% endif %}
        <br>
        <ul class="list-unstyled components mb-5 allMenuComponents" id="allMenuHide">
            <li>
                <a href="{% url 'users:main' %}"><i class="fas fa-home"
                                                    style="margin-left:1px;"></i>&nbsp;&nbsp;HOME</a>
            </li>
            <li>
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle menu1"><i
                        class="fas fa-user" style="margin:0 2.5px;"></i>&nbsp;&nbsp;My Page</a>
                <ul class="collapse list-unstyled" id="homeSubmenu">
                    <li>
                        <a href="{% url 'users:profile' %}"><i class="fas fa-user-cog"></i>&nbsp;&nbsp;내 정보</a>
                    </li>
                    <li>
                        <a href="{% url 'users:profile_post' %}"><i class="fas fa-user-edit"></i>&nbsp;&nbsp;작성한 글</a>
                    </li>
<!--                    <li>-->
<!--                        <a href="{% url 'users:profile_comment' %}"><i class="fas fa-comments"></i>&nbsp;&nbsp;댓글단 글</a>-->
<!--                    </li>-->
                </ul>
            </li>

            <li>
                <a href="#pageSubmenu1" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle menu2"><i
                        class="fas fa-pen" style="margin-right:4px;"></i>&nbsp;&nbsp;Notice</a>
                <ul class="collapse list-unstyled" id="pageSubmenu1">
                    <li>
                        <a href="{% url 'notice:notice_list' %}"><i
                                class="fas fa-clipboard-check"></i>&nbsp;&nbsp;공지사항</a>
                    </li>
                    <li>
                        <a href="{% url 'free:all_list' %}"><i
                                class="fas fa-clipboard-list"></i>&nbsp;&nbsp;자유게시판</a>
                    </li>
                    <li>
                        <a href="{% url 'anonymous:anonymous_list' %}"><i
                                class="fas fa-clipboard"></i>&nbsp;&nbsp;익명게시판</a>
                    </li>
                    <li>
                        <a href="{% url 'board:index' %}"><i class="fas fa-crown"></i>&nbsp;&nbsp;투표함</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#pageSubmenu2" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle menu3"><i class="fas fa-calendar"></i>&nbsp;&nbsp;&nbsp;Calendar</a>
                <ul class="collapse list-unstyled" id="pageSubmenu2">
                    <li>
                        <a href="{% url 'calender:calender' %}"><i class="fas fa-calendar-day"></i>&nbsp;&nbsp;일정</a>
                    </li>
                    <li>
                        <a href="http://jbnudongari.com/file/gesi_list.php?cs_ancestor=5&cs_mkey=39"><i class="fas fa-link"></i>&nbsp;&nbsp;동전관 예약 일정 바로가기</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#pageSubmenu3" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle menu4"><i
                        class="fas fa-users"></i>&nbsp;&nbsp;Pit A Pat</a>
                <ul class="collapse list-unstyled" id="pageSubmenu3">
                    <li>
                        <a href="{% url 'about:organization' %}"><i class="fas fa-sitemap"></i>&nbsp;&nbsp;동아리 조직도</a>
                    </li>
                    <li>
                        <a href="{% url 'about:pitapat' %}"><i class="fas fa-diagnoses"></i>&nbsp;&nbsp;동아리 소개</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="https://open.kakao.com/o/suLflcZf" target="_blank"><i class="fas fa-robot"></i>&nbsp;&nbsp;1:1 채팅</a>
            </li>
        </ul>

        <!--사이드바 FOOTER-->
        <div class="footer" style="position: fixed; bottom: 0; margin-left:-7px;">
            <p class="copyrightFooter">
                Copyright &copy;<script>
                document.write(new Date().getFullYear());
            </script>
                All rights<br>reserved <br><i class="icon-heart" aria-hidden="true"></i> by <a
                    href="https://www.instagram.com/pitapat___/" target="_blank">Pit_a_Pat</a>
            </p>
        </div>
    </div>
</nav>